ci(DATAGO-128713): update plugin token

diff --git a/.github/workflows/build-plugin.yaml b/.github/workflows/build-plugin.yaml
--- a/.github/workflows/build-plugin.yaml
+++ b/.github/workflows/build-plugin.yaml
@@ -174,6 +174,13 @@ jobs:
 
           exit "$TEST_RC"
 
+      - name: Verify SonarQube plugin config
+        run: |
+          if [[ ! -f "${{ inputs.plugin_directory }}/sonar-project.properties" ]]; then
+            echo "Missing sonar-project.properties in ${{ inputs.plugin_directory }}"
+            exit 1
+          fi
+
       - name: SonarQube Scan
         id: sonarqube-scan
         continue-on-error: true
@@ -184,14 +191,6 @@ jobs:
         with:
           projectBaseDir: ${{ inputs.plugin_directory }}
           args: >
-            -Dsonar.projectKey=${{ github.repository_owner }}_${{ inputs.plugin_directory }}
-            -Dsonar.projectName=${{ inputs.plugin_directory }}
-            -Dsonar.sources=src
-            -Dsonar.python.version=3.10,3.11,3.12,3.13
-            -Dsonar.sourceEncoding=UTF-8
-            -Dsonar.python.coverage.reportPaths=**/coverage.xml
-            -Dsonar.exclusions=**/__pycache__/**,**/dist/**,**/.hatch/**,**/build/**,**/*.egg-info/**,**/tests/**
-            -Dsonar.cpd.exclusions=**/tests/**
             -Dsonar.pullrequest.github.summary_comment=false
             -Dsonar.scm.disabled=true
             -Dsonar.qualitygate.wait=true
